projects:
  learnawsvue:
    schemaPath: src/aws/graphql/schema.json
    includes:
      - ''
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: ''
        docsFilePath: .
extensions:
  amplify:
    version: 3
